### ISSUE TITLE
Feature Request: Allow Customization of BuildKit State Volume (e.g., emptyDir settings or PVC)

### ISSUE THREAD

**Issue by kobin23** [andrcuns/charts#296]
Hi,

I’d like to request a feature enhancement in the Helm chart to support full customization of the volume mount used for the BuildKit state directory.

Desired Capabilities:
 • Configure emptyDir.medium (e.g., "Memory")
 • Configure emptyDir.sizeLimit
 • Optionally use a PersistentVolumeClaim (PVC) instead of emptyDir

Proposal:

Expose new values under values.yaml, such as:

```
buildkitVolume:
  type: emptyDir   # or pvc
  emptyDir:
    medium: ""
    sizeLimit: ""
  pvc:
    existingClaim: ""
    storageClassName: ""
    size: 10Gi

```

Thanks!
