### ISSUE TITLE
dependabot helm install values validation error

### ISSUE THREAD

**Issue by Legion2** [andrcuns/charts#49]
I tried using the dependabot helm chart. When installing the helm chart I get the following error:
```
failed: template: dependabot-gitlab/charts/mongodb/templates/NOTES.txt:171:4: executing "dependabot-gitlab/charts/mongodb/templates/NOTES.txt" at <include "mongodb.validateValues" .>: error calling include: template: dependabot-gitlab/charts/mongodb/templates/_helpers.tpl:272:51: executing "mongodb.validateValues" at <fail>: error calling fail:
VALUES VALIDATION:

mongodb: auth.username, auth.database
    Both auth.username and auth.database must be provided to create
    a custom user and database during 1st initialization.
    Please set both of them (--set auth.username="xxxx",auth.database="yyyy")
```

I did not set any of `auth.username` and `auth.database`. However, in the default values.yaml the auth.database is set but not the auth.username.

**Comment by andrcuns** [comment]
@Legion2 Sorry for late response.

I have not tried installing with default values actually, so there might be a bug somewhere. Will need to investigate.

**Comment by Legion2** [comment]
Should I create a PR with the values I used to get it working?

**Comment by Legion2** [comment]
To get a deterministic behavior I have set:
```yaml
mongodb:
  auth:
    database: dependabot_gitab
    username: dependabot
    password: ...
    rootPassword: ...
  strategyType: Recreate # when using standalone
redis:
  password: ...
```
